homeassistant:
  # Name of the location where Home Assistant is running
  name: HOMY home assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/share'
  allowlist_external_dirs:
    - '/share'
  legacy_templates: true
#  auth_providers:
#    - type: homeassistant
#    - type: trusted_networks
#      trusted_networks:
#        - 127.0.0.1
#        - 192.168.0.0/24

# External configuration files
group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
zone: !include zone.yaml

# This integration is a meta-component and configures a default set of integrations for Home Assistant to load.
default_config:

# The integrations that will be loaded are:
#   automation
#   cloud
#   config
#   frontend
#   history
#   logbook
#   map
#   mobile_app
#   person
#   script
#   ssdp
#   sun
#   system_health
#   updater
#   zeroconf

#shopping_list:

# Enable Python Scripts
python_script:

# HTTP - SSL
# base_url: https://alvareahomy.duckdns.org
http:
  server_port: 2309
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    #- igd
    #- xiaomi_gw
    #- esphome


# Philips Hue Bridge ==> INTEGRATION
#hue:
#  bridges:
#    - host: 192.168.0.20
#      allow_unreachable: true

# Dispositivos Apple IOS
ios:

# ALARM MANUAL CONTROL PANEL
#
#   TRANSICION: Disarmed => Armed (Home/Night/Away) => Triggered => Disarmed
#
#   STATUS      DURACION TRANSICION               DESCRIPCION
#   ========    =============================     ==================================================
#   DISARMED    Permanante                        Estado inicial de alarma desarmada
#   ARMING      <ARMING_TIME>                     Estado transición a ARMED durante <arming_time> Segundos
#   ARMED_X     Permanante                        Estado de alarma ARMED HOME / ARMED AWAY
#   PENDING     <DELAY_TIME>                      Estado transición a TRIGGERED durante <delay_time> Segundos
#   TRIGGERED   <TRIGGER_TIME>                    Estado de alarma TRIGGERED durante <trigger_time> segundos
#   ARMED_X     Permanante                        Estado anterior de alarma armada
#
alarm_control_panel:
  - platform: manual
    name: HA
    # code: !secret alarm_control_code
    # Pending: The time in seconds of the pending time before effecting a state change. Default is 60 seconds.
    # Delay: The time in seconds of the pending time before triggering the alarm. Default is 0 seconds.
    # Trigger: The time in seconds of the trigger time in which the alarm is firing. Default is 120 seconds
    code: !secret alarm_control_code
    code_arm_required: false
    arming_time: 60
    delay_time: 60
    trigger_time: 300
    disarmed:
      trigger_time: 0 # the disarmed state never triggers the alarm;
    armed_home:
      arming_time: 0

# Timer temporizadores
timer:
  piscina:
    name: Timer Piscina
    icon: mdi:timer
  riego_ch1:
    name: Timer Bonsais Top
    icon: mdi:timer
  riego_ch2:
    name: Timer CH2
    icon: mdi:timer
  riego_ch3:
    name: Timer CH3
    icon: mdi:timer
  riego_ch4:
    name: Timer CH4
    icon: mdi:timer
  riego_bonsais:
    name: Timer Bonsais Producción
    icon: mdi:timer
  riego_tomates:
    name: Timer Tomatera
    icon: mdi:timer

#counter:
#  nespresso_start:
#    initial: 0
#    step: 1

#history_graph:
#  piscina_duracion:
#    entities:
#      - binary_sensor.piscina_status
#    name: Duracion Depuradora Piscina
#    hours_to_show: 168
#    refresh: 1800

# GENERIC IP CAMERA
camera:
  - platform: generic
    still_image_url: https://api.sat24.com/mostrecent/SP/visual5hdcomplete%20width=500%20height=304
    name: Weather Satelite
  - platform: generic
    still_image_url: !secret still_image_url_cam_estudio
    name: IPcam Estudio
    username: admin
    password: !secret IPcam_estudio
  - platform: generic
    still_image_url: !secret still_image_url_cam_jardin
    ##stream_source: !secret stream_source_url_cam_jardin
    name: IPcam Jardín
    username: admin
    password: !secret IPcam_jardin

#ffmpeg:

# Mediaplayer FireTV
#media_player:
#  - platform: androidtv
#    name: Fire TV
#    host: !secret firetv_host
#    adbkey: "/config/android/adbkey"
#    ####adbkey: "/home/homeassistant/.homeassistant/config/android/adbkey"

# MQTT - BROKER: Local Mosquitto Broker
#
#mqtt:
#  broker: alvarea.duckdns.org
#  port: 1883
#  client_id: hassbian_alvarea
#  keepalive: 60
#  username: hassbian_mqtt
#  password: !secret hassbian_mqtt
#  discovery: true
#  discovery_prefix: homeassistant#

#  broker: m23.cloudmqtt.com
#  port: 11024
#  client_id: hass_alvarea
#  keepalive: 60
#  username: HASS
#  password: !secret cloudmqtt

# XIAOMI AQARA GATEWAY ==> V.0.112 = Integraciones
#xiaomi_aqara:
#  discovery_retry: 10
#  gateways:
#    - mac: !secret xiaomi_mac
#      key: !secret xiaomi_gateway

# NMAP
device_tracker:
  - platform: nmap_tracker
    hosts: !secret device_tracker_range1
    home_interval: 10
    consider_home: 0:10:00
    interval_seconds: 90
    track_new_devices: no
    #scan_options: -Pn --host-timeout 5s
    exclude:
      - !secret device_tracker_host1

  - platform: ping
    hosts:
      ping_57_amazon_kindle: 192.168.0.57

# NOTIFICACIONES
notify:
  - name: notifica_grupo_ios
    platform: group # notification group for IOS
    services:
      - service: mobile_app_iphone_aac
      - service: mobile_app_iphone_malen
      - service: mobile_app_iphone_paf
      - service: ios_aaf_ios
  - name: notifica_grupo_agus
    platform: group
    services:
      - service: mobile_app_iphone_aac
      - service: ios_aaf_ios
  - name: telegram_alarm
    platform: telegram
    chat_id: !secret telegram_grp_alarm
  - name: telegram_notify
    platform: telegram
    chat_id: !secret telegram_grp_notif
  - name: telegram_aac
    platform: telegram
    chat_id: !secret telegram_aac

# Notifications via Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
      - !secret telegram_grp_notif
      - !secret telegram_grp_alarm
      #- !secret telegram_chat_aac

alert:
  alerta_alarma_ha:
    name: ALERTA - ALARMA HOMY ACTIVADA
    done_message: Alarma Desactivada OK
    entity_id: alarm_control_panel.ha
    state: 'triggered'
    repeat: 1
    can_acknowledge: true
    skip_first: true
    notifiers:
      - telegram_alarm

  alerta_test:
    name: ALERTA - LUCES ENCENDIDAS DE DIA
    done_message: Test Alerta De Día Solucionado
    entity_id: binary_sensor.test_alert_sensor
    state: 'on'
    repeat: 1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - telegram_aac

#light:
#  - platform: group
#    name: Luces Planta Baja
#    entities:
#      - light.cocina
#      - light.dormitorio
#      - light.entrada
#      - light.pasillo
#      - light.salon
#  - platform: group
#    name: Luces Planta Alta
#    entities:
#      - light.luces_estudio
#  - platform: group
#    name: Luces Estudio
#    entities:
#      - light.estudio
#      - light.esphome_lb1_l01
#  - platform: group
#    name: Luces Interior
#    entities:
#      - light.luces_planta_baja
#      - light.luces_planta_alta

# Cloud -  Home Assistant Cloud - NABU CASA
cloud:
 alexa:
    filter:
      include_domains:
        - switch
      exclude_domains:
        - alert
        - automation
        - input_boolean
        - sensor
        - light
        - group
        - script
      include_entities:
        - light.esphome_lb1_l01
        - light.sonoff_mini_sw1
        - script.homy_armado_parcial
        - script.homy_armado_total
        - script.homy_desarmado_code
        - group.luces_estudio_grp
        - group.luces_planta_baja_grp
        - group.luces_planta_alta_grp
        - group.luces_interior_grp
        - group.luces_casa_grp
        - group.luces_jardin_grp
      exclude_entities:
        - switch.esphome_bas_sw0
        - switch.esphome_bas_sw1
        - switch.esphome_bas_sw2
        - switch.esphome_bas_sw3
        - switch.esphome_bas_sw4
        - switch.esphome_pow_sw1
        - switch.esphome_pow_sw2
        - light.luz_cilindro
        - light.luz_cueva_agu
        - light.luz_dormitorio_aac
        - light.luz_dormitorio_mfc
        - light.luz_entrada
        - light.luz_estudio
        - light.luz_lectura
        - light.luz_tv
        - light.luz_pasillo
        - light.luz_vitrina
        - light.entrada
        - light.cocina
        - light.estudio
        - light.pasillo
        - light.salon
        - light.dormitorio_aaf
        - light.dormitorio_paf
    entity_config:
      script.homy_armado_parcial:
        name: Armado Parcial
      script.homy_armado_total:
        name: Armado Total
      script.homy_desarmado_code:
        name: !secret desarmado_code
      group.luces_toda_la_casa_grp:
        name: Luces Toda La Casa
        description: Luces Interior y Exterior
      group.luces_jardin_grp:
        name: Luces Jardín
      light.sonoff_mini_sw1:
        display_categories: LIGHT
        name: Luces Exterior
      switch.esphome_pow_sw1:
        display_categories: LIGHT
        name: Arbol Navidad
      switch.esphome_4ch_relay_1:
        display_categories: LIGHT
      switch.esphome_4ch_relay_2:
        display_categories: LIGHT
      switch.esphome_4ch_relay_3:
        display_categories: LIGHT
      switch.esphome_4ch_relay_4:
        display_categories: LIGHT
      switch.esphome_bas_sw1:
        display_categories: LIGHT
      switch.esphome_bas_sw4:
        display_categories: LIGHT
      light.esphome_lb1_l01:
        display_categories: LIGHT
      script.luces_dormitorio_lectura:
        name: Dormitorio Lectura
      script.luces_dormitorio_relax:
        name: Dormitorio Relax
      script.luces_dormitorio_tenue:
        name: Dormitorio Tenue
      script.luces_dormitorio_noche:
        name: Dormitorio Noche
      script.luces_salon_relax:
        name: Salon Relax
      script.luces_salon_luminosa:
        name: Salon Top
      script.luces_salon_wpt:
        name: Salon Azul
      script.luces_estudio_Top:
        name: Estudio Top
      script.luces_estudio_relax:
        name: Estudio Relax
recorder:
  # purge_interval: 1
  purge_keep_days: 30
  exclude:
    domains:
      - input_boolean
      - input_text
      - input_select
      - media_player
      - camera
      - automation
      - climate
      - group
      - script
      - sun
      - weather
      - zone

weather:
  - platform: darksky
    api_key: !secret weather_apikey
    mode: daily
    latitude: !secret latitude_home
    longitude: !secret longitude_home

#apcupsd:
#  host: 127.0.0.1
#  port: 3551
#  mode: netserver

person:

# The stream component provides a way to proxy live streams through Home Assistant.
# The component currently only supports the HLS format.
stream:

blink:
  username: !secret blink_usr
  password: !secret blink_pwd
  scan_interval: 600
  #binary_sensors:
  #  monitored_conditions:
  #    - motion_enabled
  #    - motion_detected
  #sensors:
  #  monitored_conditions:
  #    - battery

#
# Sensores Xiaomi Flower Care - Componente Plant - Integracion ESPHOME - ESP32S Hub BLE ESP32S
#
plant:
  mp_01:
    sensors:
      moisture: sensor.humedad_plant_monitor_pm01
      temperature: sensor.temperatura_plant_monitor_pm01
      conductivity: sensor.fertilidad_plant_monitor_pm01
      brightness: sensor.luminosidad_plant_monitor_pm01
      # battery: sensor.miflora_s1_bateria
    min_moisture: 20
    max_moisture: 50
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 38
    min_brightness: 2000
    max_brightness: 50000
  mp_02:
    sensors:
      moisture: sensor.humedad_plant_monitor_pm02
      temperature: sensor.temperatura_plant_monitor_pm02
      conductivity: sensor.fertilidad_plant_monitor_pm02
      brightness: sensor.luminosidad_plant_monitor_pm02
      # battery: sensor.miflora_s1_bateria
    min_moisture: 20
    max_moisture: 50
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 38
    min_brightness: 2000
    max_brightness: 50000
  mp_03:
    sensors:
      moisture: sensor.humedad_plant_monitor_pm03
      temperature: sensor.temperatura_plant_monitor_pm03
      conductivity: sensor.fertilidad_plant_monitor_pm03
      brightness: sensor.luminosidad_plant_monitor_pm03
      # battery: sensor.miflora_s1_bateria
    min_moisture: 20
    max_moisture: 50
    min_conductivity: 50
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 38
    min_brightness: 2000
    max_brightness: 50000

sonoff:
  username: !secret sonoff_ewelink_user
  password: !secret sonoff_ewelink_pwd
  devices:
    1000b4adc4:
      device_class: light
      name: Luz Exterior
    1000b5aa49:
      device_class: light
      name: Luz Escritorio
    1001057e5c:
      device_class: light
      name: Switch SW3
    100104fe64:
      device_class: light
      name: Switch SW4
    1000f83c56:
      device_class: light
      name: Switch BAS SW3
    10011a769f:
      name: Switch S20 SW2

# iCloud Calendar Integration - CALDAV
calendar:
  - platform: caldav
    username: !secret icloud_usr
    password: !secret icloud_pwd
    url: !secret icloud_url
    calendars:
    custom_calendars:
      - name: Universidad_AAF
        calendar: Family
        search: "Universidad AAF"
      - name: Universidad_PAF
        calendar: Family
        search: "Universidad PAF"
      - name: Almuerzo
        calendar: Family
        search: "Almuerzo"
      - name: Cena
        calendar: Family
        search: "Cena"



#
# DEPRECATED
#
# Sensores Xiaomi BLE Temperatura, utilizando el componente custom HACS: ble_monitor ==> DEPRECATED
# Paso a componente ESPHOME_ESP32_Hub2_BLE
#ble_monitor:
#  rounding: True
#  decimals: 1
#  period: 60
#  log_spikes: False
#  use_median: False
#  active_scan: False
#  hci_interface: 0
#  batt_entities: False
#  report_unknown: False
#  discovery: False
#  devices:
#    - mac: 'A4:C1:38:6B:AA:C8'  # Estudio
#      encryption_key: 'A7EC07B7EDC9D349CC462CB9744AC756'
#    - mac: 'A4:C1:38:E8:02:EF'  # Rack Armario
#      encryption_key: 'A5ED5C2C2D9D3E14C1894ADFEEF46E1C'
#    - mac: 'A4:C1:38:4B:D6:7C'  # Exterior
#      encryption_key: 'DACA7EDCEF444035A7B8C40600A4A99E'

# Old Configuration mi_temp custom component before migration to 0.81 ==> ble_monitor:
#- sensor:
#  - platform: mi_temp
#      rounding: True
#      decimals: 1
#      period: 60
#      log_spikes: False
#      use_median: False
#      active_scan: False
#      hci_interface: 0
#      batt_entities: False
#      report_unknown: False
#      whitelist: False
#      encryptors:
#        'A4:C1:38:6B:AA:C8': 'A7EC07B7EDC9D349CC462CB9744AC756'
#        'A4:C1:38:E8:02:EF': 'A5ED5C2C2D9D3E14C1894ADFEEF46E1C'
#        'A4:C1:38:4B:D6:7C': 'DACA7EDCEF444035A7B8C40600A4A99E'

#
#  Sensores Miflorea - Basado en Sensor Bluetooth Nativo Rasperry y Componente mitemp_bt
#  miflora_s1:
#    sensors:
#      moisture: sensor.mi_m_c47c8d67c19e
#      battery: sensor.mi_b_c47c8d67c19e
#      temperature: sensor.mi_t_c47c8d67c19e
#      conductivity: sensor.mi_c_c47c8d67c19e
#      brightness: sensor.mi_l_c47c8d67c19e
#    min_moisture: 20
#    max_moisture: 60
#    min_conductivity: 350
#    max_conductivity: 2000
#    min_temperature: 10
#    max_temperature: 32
#    min_brightness: 1000
#    max_brightness: 30000
#    min_battery: 20

# TV Sony
# media_player:
#   - platform: braviatv
#     host: 192.168.0.14
#     name: TV Sony Salón
#   - platform: braviatv
#     host: 192.168.0.15
#     name: TV Sony Estudio

#TO DO
#
# https://github.com/custom-components/custom_updater/wiki/Installation
# custom_updater:
#  card_urls:
#    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
