#
# CERTBOT SSL CERTIFICATE: ALERT TO WARN US IF SOMETHING WENT WRONG.
#
- id: S1_ssl_expiry_notification
  alias: 'S1 SSL expiry notification'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry
    below: 15
  action:
    service: script.turn_on
    entity_id: script.notifica_evento
    data:
      variables:
        title: '*CERTIFICADO SSL*'
        message: >
          >>> EVENTO: El certificado SSL expira en {{ states('sensor.ssl_certificate_expiry') }}


#
# REGLA: AVISO ALARMA POR SENSOR VIBRACION EN PUERTA RACK COMUNICACIONES ESTUDIO
#
- id: A12
  alias: 'A12 Alarm Sensor Vibracion Rack Estudio'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.movement
      event_data:
        entity_id: binary_sensor.vibration_158d0002b15e3b
        action_type: vibrate
    - platform: event
      event_type: xiaomi_aqara.movement
      event_data:
        entity_id: binary_sensor.vibration_158d0002b15e3b
        movement_type: tilt
  condition:
    - condition: state
      entity_id: input_boolean.rack_sensor_vibration_disable
      state: 'off'
  action:
    # Script Notificación Evento
    - service: script.turn_on
      entity_id: script.notifica_evento
      data:
        variables:
          title: '*ALARMA HOMY*'
          message: >
            >>> SENSOR VIBRACION: RACK COMUNICACIONES
            >>> SALA: ESTUDIO


#-----------------------------------------------------------------------------#
#                                                                             #
#FAMILY META TRACKER HOME/AWAY                                               #
#                                                                             #
#-----------------------------------------------------------------------------#
#
#MFC_Trackers = ['device_tracker.mfc_iphone_nmap',
#                'device_tracker.mfc_iphone_owntrack',
#                'device_tracker.iphone_malen' ]
#                'device_tra'cker.b6cd9e1f_4100_4cac_88d0_f4d6c044a4e6']
#
#AAC_Trackers = ['device_tracker.aac_iphone_nmap',
#                'device_tracker.aac_iphone_owntrack',
#                'device_tracker.iphone_aac',
#                'device_tracker.b8b52a3b_f038_4e72_a268_705d9b06e496']
#
#PAF_Trackers = ['device_tracker.paf_iphone_nmap',
#                'device_tracker.paf_iphone_owntrack',
#                'device_tracker.iphone_paf',
#                'device_tracker.863b93f2_f00f_4737_a35f_1ff0cce201a8']
#
#AAF_Trackers = ['device_tracker.aaf_iphone_nmap',
#                'device_tracker.a2f',
#                'device_tracker.0b495ff5_94fc_4773_9644_f71df3c328ac']
- id: U1
  alias: "Update Device Meta Tracker"
  initial_state: 'on'
  trigger:
    # Delayed action for router-based and Owntracks trackers that are not 100% reliable
    - platform: state
      entity_id:
        - device_tracker.aac_iphone_nmap        # NMAP
        - device_tracker.mfc_iphone_nmap        # NMAP
        - device_tracker.paf_iphone_nmap        # NMAP
        - device_tracker.aaf_iphone_nmap        # NMAP
        - device_tracker.aac_iphone_owntrack    # OWNTRACK
        - device_tracker.mfc_iphone_owntrack    # OWNTRACK
        - device_tracker.paf_iphone_owntrack    # OWNTRACK
      to: 'not_home'
      for: '00:07:00'
    - platform: state
      entity_id:
        - device_tracker.aac_iphone_owntrack    # OWNTRACK
        - device_tracker.mfc_iphone_owntrack    # OWNTRACK
        - device_tracker.paf_iphone_owntrack    # OWNTRACK
      to: 'home'
    - platform: state
      entity_id:
        - device_tracker.aac_iphone_nmap      # NMAP
        - device_tracker.mfc_iphone_nmap      # NMAP
        - device_tracker.paf_iphone_nmap      # NMAP
        - device_tracker.aaf_iphone_nmap      # NMAP
      to: 'home'
      for: '00:00:30'
    - platform: state
      entity_id:
        - device_tracker.iphone_aac                               # IOSAPP
        - device_tracker.iphone_malen                             # IOSAPP
        - device_tracker.iphone_mfc                               # IOSAPP
        - device_tracker.a2f                                      # IOSAPP
        - device_tracker.b6cd9e1f_4100_4cac_88d0_f4d6c044a4e6     # MFC
        - device_tracker.b8b52a3b_f038_4e72_a268_705d9b06e496     # AAC
        - device_tracker.863b93f2_f00f_4737_a35f_1ff0cce201a8     # PAF
        - device_tracker.0b495ff5_94fc_4773_9644_f71df3c328ac     # AAF
  action:
    - service: script.updatetracker
      data:
        entityid: '{{trigger.entity_id}}'
        fromstate: '{{trigger.from_state.state}}'
        tostate: '{{trigger.to_state.state}}'
