#
# ESPHOME SONOFF POW R2 SW2 - LAVADORA
#
# FTDDI CABLE 1 ROJO-VERDE
#   GND => VERDE
#   R   => ROJO
#   TX  => NARANJA
#   VCC => AMARILLO - 3.3V
#
esphome:
  name: esphome_pow_sw2
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid_wlan
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 192.168.0.37
    gateway: !secret wifi_gateway
    subnet: 255.255.255.0

api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "esphome pow sw2 boton"
  - platform: status
    name: "esphome pow sw2 status"


switch:
  - platform: gpio
    name: "esphome pow sw2"
    pin: GPIO12

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: pow_sw2_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "esphome pow sw2 led"
    output: pow_sw2_green_led

# Example configuration entry
# Disable logging over USB
logger:
  # baud_rate: 115200
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 30s
    current:
      name: "esphome pow sw2 Current"
    voltage:
      name: "esphome pow sw2 Voltage"
    power:
      name: "esphome pow sw2 Power"
